### PR TITLE
Report S3 URL instead of local file path when S3 is used.

### PR DESCRIPTION
**Pull request by iggant**
To make https://github.com/mattheworiordan/capybara-screenshot/pull/221 merged, I just rebase PR without edit.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
I will do a release shortly with this change.

**Comment by mattheworiordan** [comment]
Thanks again for this contribution.

**Comment by wbotelhos** [comment]
Hi,

Could we avoid the following line:

```
s3_region = s3_client.get_bucket_location(bucket: bucket_name).location_constraint
```

With a configuration to avoid this request? This request need to be ignored by Webmock too and it breaks the things and, of course, is one more overhead.

**Comment by rzaharenkov** [comment]
@wbotelhos it makes a lot sense, taking into account that we don't need region in order to build S3 public URL. Unfortunately I don't have neither time nor test environment to work on it. Could you please create an issue. it should be quite easy to fix:

`send("#{type}_path=", "https://#{bucket_name}.s3-#{s3_region}.amazonaws.com/#{s3_upload_path}")` => `send("#{type}_path=", "https://#{bucket_name}.s3.amazonaws.com/#{s3_upload_path}`

**Comment by mattheworiordan** [comment]
@wbotelhos indeed, I'd welcome a PR to fix this issue.

**Pull request merged**
