### PR TITLE
Only take screenshots for features tests

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
ping!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by mattheworiordan** [comment]
Sorry @n-rodriguez for the delay.  Been away a bit and been very busy of late, not writing much code sadly.

The issue I have merging this right now is that all the builds are failing.  This happened before some time back because of changed dependencies in the test suites, which means I need to spend time getting things passing again.  Making this change may have unexpected side effects 😟 

I realise it's a big ask, but I really won't have time for a while to look into this properly. Do you think you would?

**Comment by mattheworiordan** [comment]
@n-rodriguez you may want to rebase this on `master` now to see if this works and CI passes.  It should do as CI is now passing, unless this work does in fact break the builds.

**Comment by n-rodriguez** [comment]
Tests are running :)

**Comment by n-rodriguez** [comment]
btw Ruby 2.0 / 2.1 / 2.2 are now obsolete : https://www.ruby-lang.org/en/downloads/branches/

**Comment by mattheworiordan** [comment]
> btw Ruby 2.0 / 2.1 / 2.2 are now obsolete 

Sure, but that does not mean we don't support those versions i.e. our library is as backwards compatible as possible, unless a particular version introduces particular onerous issues.  Best of luck :)

**Comment by n-rodriguez** [comment]
> Sure, but that does not mean we don't support those versions i.e. our library is as backwards compatible as possible, unless a particular version introduces particular onerous issues. Best of luck :)

fair enough

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by n-rodriguez** [comment]
Hi there! Any news? Use it for a while and it works perfectly :)

**Comment by mattheworiordan** [comment]
Ah, excellent. Merging now.  Sorry for the delay @n-rodriguez and thanks for the contribution

**Comment by mattheworiordan** [comment]
Released, see https://rubygems.org/gems/capybara-screenshot/versions/1.0.20

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
