### PR TITLE
take screenshots of correct window

### LINKED ISSUE #143: Screenshots are not taken when using multiple windows
Hi,

When I use the capybara window api, with methods such as `open_new_window`, `switch_to_window`, et al, in the case of an error, no screenshots are saved.

Is this intended behavior ?

Thanks !

### PR DESCRIPTION
**Pull request by dreyks**
fixes #143 

unfortunately couldn't figure out how to properly test this - base capybara driver is not capable of switching windows

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Thanks for this contribution @dreyks, however this code is not threadsafe AFAICT.  Capybara Screenshot does indeed share static variables, however unless there is a bug, the idea is that session (test) specific state is not stored at a static class level for obvious reasons (parallel tests).  Would you be able to look into a way to use a test local variable instead?

**Comment by dreyks** [comment]
🤔 At first I've been thinking about that but then I saw some other places of direct writing into a static variable like this
https://github.com/mattheworiordan/capybara-screenshot/blob/cac1beedff40a5fb7cf46853b35f2c97f5a1eafd/lib/capybara-screenshot/capybara.rb#L18

But I think I can store the offending window in the capybara session (or page) itself

**Comment by mattheworiordan** [comment]
> At first I've been thinking about that but then I saw some other places of direct writing into a static variable like this

Mmm, that's not good.  I'll raise an issue to fix that too down the line.

**Comment by trcarden** [comment]
@mattheworiordan and @dreyks Has this stalled out? I found myself also in a situation where it would be quite nice to the the screenshot from the new window.

**Comment by mattheworiordan** [comment]
> Has this stalled out?

Yup, waiting on @dreyks to update I am afraid.

**Comment by cgunther** [comment]
@trcarden check out #287

**Comment by mattheworiordan** [comment]
Closing as superseded by https://github.com/mattheworiordan/capybara-screenshot/pull/287

**Pull request closed without merging**
