### PR TITLE
Report S3 URL instead of local file path when S3 is used.

### PR DESCRIPTION
**Pull request by rzaharenkov**

### CODE REVIEW

**Comment by AKoetsier** [comment]
Would also be nice if you could generate signed urls to view the screenshots, that way you don't have to have an AWS account or set the images to public.

**Comment by rzaharenkov** [comment]
@AKoetsier, I've created a separate bucket for screenshots and made it public. Do you see any risks or problems with it?

**Comment by AKoetsier** [comment]
Well it is bad practice to open up your bucket to the world if you don't want everyone to see it. I would like to limit access since we only want to allow people who are able to login to drone to see the images. You can do that with signed urls.

**Comment by AKoetsier** [comment]
I have created a small patch that allows me to do so, I will try to push it this week.

**Comment by ypresto** [comment]
I have just setup s3 upload and found this issue. Could you push the patch? Thanks!

**Comment by iggant** [comment]
can you please concider to merge this, 
we're using bitbucket pipelines so local path is not very usefull, and really there is not much security with the public available screenshots

**Comment by mattheworiordan** [comment]
@rzaharenkov apologies I did not reply.  I missed this somehow.  Thank you for the contribution.

However, it's not passing CI is green.  Would you mind rebasing to see if it now passes CI, and if does, I promise to quickly get this merged and get a release out.

@iggant thanks for the nudge.

**Comment by leshik** [comment]
@rzaharenkov would be nice to have base URL configurable... so that one could use any compatible object storage, such as `minio`. I'm using `minio` gateway to GCS, for example, so even the gateway URLs won't work.

**Comment by mattheworiordan** [comment]
This is now resolved in https://github.com/mattheworiordan/capybara-screenshot/pull/239

**Pull request closed without merging**
