### PR TITLE
Ensure screenshot taken on expect() failures

### LINKED ISSUE #212: Screenshots are not taken for expectation failures
Consider a feature spec with this expectation:

```ruby
expect(page).to have_css(".foo")
```

If this expectation fails, I assume that this gem should take a screenshot. But surprisingly it does not.

A screenshot is only taken if I rewrite the spec as:

```ruby
expect(page.find(".foo")).to be_present
```

I much prefer the first syntax, and it is also the style suggested by the Capybara docs.

The reason the second version works is because `find` raises an exception if it fails.

Otherwise, my understanding is that a failed `expect` (as in the first example) does not set `example.exception`, and therefore [this test](https://github.com/mattheworiordan/capybara-screenshot/blob/df720a609a0186f7e24e43c7e36c96bbd84635cd/lib/capybara-screenshot/rspec.rb#L55) in capybara-screenshot evaluates to `false`, meaning the screenshot will not be taken.

```ruby
if Capybara.page.current_url != '' && Capybara::Screenshot.autosave_on_failure && example.exception
                                                                                  ^^^^^^^^^^^^^^^^^
```

What is the reasoning behind limiting screenshots to exceptions only, and can this be changed? Or perhaps made configurable? I would be happy to contribute a PR.

Otherwise there is an entire style of tests that simply won't produce screenshots on failures, like:

```ruby
expect(page).to have_content "..."
expect(page).to have_css "..."
expect(page).to have_current_path "..."
# etc.
```

I'm using:

```
capybara (2.14.4)
capybara-screenshot (1.0.17)
rspec (3.6.0)
rspec-core (3.6.0)
rspec-expectations (3.6.0)
rspec-mocks (3.6.0)
rspec-rails (3.6.0)
rspec-support (3.6.0)
```

### PR DESCRIPTION
**Pull request by mattbrictson**
Starting with RSpec 3.3.0, `expect()` failures do not raise an exception immediately. Instead each failure is recorded in a thread-local "aggregator" and then raised at end of the example.

This interferes with capybara-screenshot because `after` hooks execute *before* these aggregated failures are raised. In other words, in the `after` block `example.exception` will be `nil`. This makes capybara-screenshot think that the example hasn't failed, and thus it does not take a screenshot, even though there are actual failures.

This PR works around this problem by using some behind-the-scenes knowledge of how rspec-expectations does the aggregation. Now we reach into the thread-local storage (`RSpec::Support.failure_notifier`) and discover whether there are in fact failures "queued up". If so, we will consider the example to have failed and take a screenshot.

---

Fixes #212

~~This PR is incomplete: I still need to add tests, etc.~~ The PR is ready to merge.

### CODE REVIEW

**Comment by mattheworiordan** [comment]
@mattbrictson I really like where this is going, than you.  I think that in order to merge this in, we'd definitely need to modify the Appraisals config to include the latest version of RSpec. See https://github.com/mattheworiordan/capybara-screenshot/blob/master/.travis.yml#L13 and https://github.com/mattheworiordan/capybara-screenshot/blob/master/Appraisals#L1-L3.  See https://github.com/thoughtbot/appraisal for more info on the Appraisal gem.

Shout if I can help with anything, but if you can show that this works with 3.0 and 3.3 with separate appraisals, I'd say we're good to go.

Thanks again, 👍

**Comment by mattbrictson** [comment]
I've added a test and included rspec 3.3 in the Appraisal and Travis configs. So this PR is mostly good to go.

The problem is that [Travis fails for Ruby 2.0](https://travis-ci.org/mattheworiordan/capybara-screenshot/jobs/259978708#L249), due to nokogiri no longer supporting that version. I've tried a couple different approaches to work around the problem (see a146f96 and 51d2ddd) unsuccessfully.

I am not super-familiar with Appraisal so perhaps there is a solution that I am missing. Any suggestions?

**Comment by mattbrictson** [comment]
Problem solved! See efd81c6.

@mattheworiordan I think this PR is ready for your review when you have a chance. Thanks!

**Comment by mattbrictson** [comment]
My team has been using this branch for several weeks with no problems. I'd be great to get this merged!

**Comment by AndreiH** [comment]
Thank you @mattbrictson for this. It looks good.
@mattheworiordan can we get this modifications approved ? :D

**Comment by arkaitzgarro** [comment]
Same here, it works nice for us as well. Thank you @mattbrictson. @mattheworiordan can we make it happen? 🙏

**Comment by AndreiH** [comment]
@mattheworiordan Any updates on this ? Please please please

**Comment by mattheworiordan** [comment]
Sorry all, I have been very sh*t of late.  I am merging now and bumping the version.
Thank you VERY MUCH @mattbrictson for this contribution!

**Comment by mattheworiordan** [comment]
@mattbrictson https://github.com/mattheworiordan/capybara-screenshot/commit/92aaddcca91cadcb73639b9e54a61f1b642e567c#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR7 🙏

**Pull request merged**
