### PR TITLE
take screenshots of correct window (Updated)

### LINKED ISSUE #143: Screenshots are not taken when using multiple windows
Hi,

When I use the capybara window api, with methods such as `open_new_window`, `switch_to_window`, et al, in the case of an error, no screenshots are saved.

Is this intended behavior ?

Thanks !

### PR DESCRIPTION
**Pull request by cgunther**
This is a continuation of #245, starting with @dreyks's work and trying to address @mattheworiordan's feedback.

Fixed #143

### CODE REVIEW

**Review by mattheworiordan — APPROVED** [review]
This looks great.  Thank you for the contribution @cgunther

**Comment by cgunther** [comment]
Thanks for the merge!

I saw you bumped/tagged the version (6b80ac24fafa1e92052168807cc1dff2fa471af6) to `v1.0.26`, but looks like the gem didn't get pushed to RubyGems yet, it's still showing `v1.0.25`:
https://rubygems.org/gems/capybara-screenshot

**Comment by mattheworiordan** [comment]
Oops, that's odd. I will look into this now.

**Comment by mattheworiordan** [comment]
Ok, fixed, apologies for that

**Comment by cgunther** [comment]
Thanks!

**Comment by AlexWayfer** [comment]
As I understood, this has been released as `1.0.26` at January 2022.

But I have an issue with 2 windows, probably it's another one, but you can help me (describe and ensure).

I'm using a separate driver for `incognito` mode, and `Capybara.using_driver(:selenium_incognito) do` works good with it (opens actually the second window), but at fail there (for example, `click_button` can't find) I'm getting a screenshot from the first (main) window.

**Pull request merged**
