### PR TITLE
Add apparition driver

### PR DESCRIPTION
**Pull request by sedubois**
see https://github.com/mattheworiordan/capybara-screenshot/issues/241#issuecomment-500608903

### CODE REVIEW

**Comment by mattheworiordan** [comment]
Thanks!

**Comment by amomchilov** [comment]
@mattheworiordan Hey Mathew, could you please release this commit as a `v1.0.24`? This is the only commit since `v1.0.23` was released on June 10.

I'm currently using `gem 'capybara-screenshot', github: 'mattheworiordan/capybara-screenshot', ref: '273317b241d1d1d8600b32fad998742894424f3b'`, but it'd be better to depend on a regular version instead.

**Comment by mattheworiordan** [comment]
@amomchilov sorry, I thought it had been released.  I am on a new laptop so not set up quite yet, but will look at this this week if I can and do a release.

**Comment by amomchilov** [comment]
Ok, thanks!

**Comment by mattheworiordan** [comment]
P.S. This is now released https://rubygems.org/gems/capybara-screenshot.  Thanks again for the contribution.

**Comment by amomchilov** [comment]
Cheers, thanks for maintaining this!

**Pull request merged**
